Fixed: Map js loading everywhere
10up/maps-block-apple pull request #161
Opened 2023-02-14 13:22 UTC by jayedul

### Description of the Change
Map js library was loading everywhere. Now it is fixed.

Closes #147 

### How to test the Change
- Create a page or post
- Add Apple Map block
- Save and visit
- Open network log and make sure `https://cdn.apple-mapkit.com/mk/5.x.x/mapkit.js` is loading
- Now edit the post, remove the map block, save and visit again
- Now you should see the library is not loading anymore. Previously it used load even though there is no map block in the post. 

### Changelog Entry

> Fixed - Mapkit js loading everywhere in frontend despite no Map block there is

### Credits

Props @jayedul 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-02-14 14:25 UTC, fabiankaegy requested changes
Thanks for your contribution :) 

The change currently only adds the `apple-mapkit-js` dependencie to the editor script of the block. However it also needs to be present in the script we load on the frontend via the `viewScript` handle: `maps-block-apple-frontend`

However I still don't quite understand why the script is loading everywhere. As per the documentation any `WPDefinedAsset` loaded via the `script` key should only be enqueued in the editor and on the frontend if the block is actually being used.  https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-metadata.md#script

2023-02-14 15:50 UTC, jayedul commented
`apple-mapkit-js` is already used as dependency for frontend.  
<img width="920" alt="s" src="https://user-images.githubusercontent.com/12506700/218787055-9037c2e6-c802-4a06-80c2-1682674a6d41.png">

However, I'm also unsure why the file loads everywhere when it was registered with `script` key.

2023-09-01 15:04 UTC, jeffpaul commented
@fabiankaegy @jayedul is there still work needed here or can this move along in review and towards merge?

2023-10-10 01:01 UTC, jeffpaul commented
@10up/open-source-practice would be good if someone could help get this through review/merge... thanks!

2023-10-10 09:19 UTC, faisal-alvi approved these changes
LGTM

Working as expected:

![image](https://github.com/10up/publisher-media-kit/assets/25176325/7a6f43a8-2473-41c1-a4e7-e7ca6c917523)

IMO, no more work is required; looks good to merge.

2023-10-10 13:54 UTC, merged