#85 - Enqueue map assets only when being used / Clean up unused assets
10up/maps-block-apple pull request #97
Opened 2021-10-01 10:12 UTC by joshuaabenazer

### Description of the Change

Enqueue map assets only when being used / Clean up unused assets

### Alternate Designs

None.

### Benefits

It will optimize page load times by only enqueuing assets when required.

### Possible Drawbacks

None.

### Verification Process

- Cross check the maps settings page and make sure only the required js/css files for the particular settings page is loading.
- Cross check the post edit screen with Gutenberg enabled to make sure no frontend related map scripts are being loaded.
- Cross check frontend of the site to ensure only on posts that have apple maps block, the maps assets are being loaded.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

None.

### Changelog Entry

Enqueue map assets only when being used / Clean up unused assets

2021-10-01 10:19 UTC, fabiankaegy requested changes
@joshuaabenazer I actually just took a look at something simmilar also. I think we can improve this by still keeping all the references to the scripts & styles in the `block.json` file. But instead of referencing the file there you can pass the handle of the registered script. 

WordPress should then take care of only enqueueing the assets in the correct areas. 

So yes we should not `enqueue` apple maps directly but only register it and add it to the dependencies of the editor and frontend script. But instead of doing the `has_block` check manually I think it would be better to rely on WordPress to do that. Especially when we think of more than just the editor as possible context for blocks (widgets or even Full Site Editing)

You can see an example of how that would work here: https://github.com/WordPress/gutenberg/blob/456eabc9f574e449863acbb3c4f12495485f15b8/packages/e2e-tests/plugins/iframed-block/block.json#L12

https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/plugins/iframed-block.php#L20-L25

2021-10-07 11:30 UTC, joshuaabenazer commented
@fabiankaegy I actually tried doing that the first time around, but wasn't getting the expected results and couldn't find much about that online too. I will give it another go and see.

2021-10-11 09:18 UTC, fabiankaegy reviewed
Thank you for working on this :) I added some comments that I think will make it a bit more concise. Let me know if you have any questions :) 🚀

2021-10-11 09:18 UTC, fabiankaegy commented on block.json
> +	"editorScript": "file:build/index.js",
instead of registering the file here, we are also able to pass it the handle with which we have registered the stript. So `maps-block-apple-block` in this case
```suggestion
	"editorScript": "maps-block-apple-block",
```

2021-10-11 09:18 UTC, fabiankaegy commented on block.json
> +	"script": "file:build/frontend.js"
Same here:
`maps-block-apple-frontend`

```suggestion
	"script": "maps-block-apple-frontend"
```

2021-10-11 09:18 UTC, fabiankaegy commented on includes/block-assets.php
> +			'editor_script' => 'maps-block-apple-block',
By adding the handle in the `block.json` file instead of the file we don't need to override it here

2021-10-11 09:19 UTC, fabiankaegy commented on includes/block-assets.php
> +			'editor_script' => 'maps-block-apple-block',
For this we may even be able to completely remove the two properties and _just_ pass the directory of the `block.json` file in. That sould give it all the info it needs

2021-10-11 09:21 UTC, fabiankaegy commented on includes/block-assets.php
> +			'editor_script' => 'maps-block-apple-block',
Not sure wether I have the correct variable here but something like this:

```php
register_block_type( MAPS_BLOCK_APPLE_PATH );
```

2021-10-11 12:13 UTC, joshuaabenazer commented
@fabiankaegy this has been a great learning experience. I have updated the code accordingly, but I also tried to override some attributes within the client side block registration. Let me know what you think about that.

2021-10-11 12:57 UTC, fabiankaegy commented on src/index.js
> +registerBlockType( metadata, {
Does this currently work? I thought the `registerBlockType` function in js needs the first param to be the block name and the second the block options. So

```js
import metadata from '../../block.json;

registerBlockType(
    metadata.name,
    {
        ...metadata,
        edit: MapsBlockAppleEdit,
        save: MapsBlockAppleSave,
    }
)
```

but I could be totally wrong here :)

2021-10-11 12:58 UTC, fabiankaegy commented on block.json
> +      "default":"standard"
This is a great catch :)

2021-10-11 12:59 UTC, fabiankaegy commented on block.json
> +      "default":"adaptive"
also here great catch :)

2021-10-11 13:02 UTC, joshuaabenazer commented on src/index.js
> +registerBlockType( metadata, {
@fabiankaegy I also thought so, but if you check the client side example here at the end -> https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#javascript-client-side you can see we just need to metadata as a whole.
But since we needed to extend some dynamic values it looks like that.

2021-10-11 13:05 UTC, fabiankaegy commented on src/index.js
> +registerBlockType( metadata, {
Okay, fascinating :) Thank you for sharing that! 

Then the final question, why do you manually define the `attributes` in the dynamic object again? 
My assumption would be that this would already be there from the entire `metadata` object in the first prop.

2021-10-11 13:06 UTC, fabiankaegy commented on src/index.js
> +registerBlockType( metadata, {
Never mind 🤦 =D

2021-10-11 13:11 UTC, fabiankaegy submitted a review, later dismissed
This is looking and working great :) Thanks for your contribution! :) 🚀

2021-10-11 13:14 UTC, fabiankaegy commented
@joshuaabenazer I just saw that there are some `eslint` issues that need to get solved before github would let us merge. So once they are done this is approved to get merged :)

2021-10-11 16:11 UTC, fabiankaegy approved these changes

2021-10-11 16:12 UTC, fabiankaegy commented
@jeffpaul @helen Is one of you able to help us merge this? The failed `phpcs` issue has nothing to do with this PR

2021-10-11 16:26 UTC, merged